defaults: &DEFAULTS
  default:
    user_id: <%= ENV['EBSCO_USER'] %>
    password: <%= ENV['EBSCO_PASSWORD'] %>
    profile: <%= ENV['EBSCO_PROFILE'] %>

  other:
    ...

development:
  <<: *DEFAULTS

integration:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS