# = jetty_path key
# each environment can have a jetty_path with absolute or relative
# (to app root) path to a jetty/solr install. This is used
# by the rake tasks that start up solr automatically for testing
# and by rake solr:marc:index.
#
# jetty_path is not used by a running Blacklight application
# at all. In general you do NOT need to deploy solr in Jetty, you can deploy it
# however you want.
# jetty_path is only required for rake tasks that need to know
# how to start up solr, generally for automated testing.
# 

integration:
  url: http://da-prod-solr7.library.cornell.edu/solr/b7
  #url: http://da-dev-solr.library.cornell.edu/solr/test
  #url: http://dasolr.library.cornell.edu/solr/blacklight2
  #url: http://da-dev-solr.library.cornell.edu/solr/blacklight
  #url: http://da-stg-ssolr.library.cornell.edu/solr/blacklight

development:
  url: http://da-prod-solr7.library.cornell.edu/solr/b7
  #url: http://da-prod-solr10.library.cornell.edu:8983/solr/b6
  #url: http://da-dev-solr.library.cornell.edu/solr/test
  #url: http://dasolr.library.cornell.edu/solr/blacklight2
  #url: http://da-prod-solr1.library.cornell.edu/solr/blacklight2
  #url: http://dasolr.library.cornell.edu/solr/blacklight2

test: &test
  url: http://da-prod-solr7.library.cornell.edu/solr/b7
  #url: http://da-dev-solr.library.cornell.edu/solr/test
  #url: http://dasolr.library.cornell.edu/solr/blacklight2
  #url: http://da-dev-solr.library.cornell.edu/solr/test

production:
  url: http://da-prod-solr.library.cornell.edu/solr/blacklight
  #url: http://da-stg-ssolr.library.cornell.edu/solr/blacklight

cucumber:
  <<: *test
